application: rowcalc
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /api/.*
  script: api/index.php

- url: /api
  script: apihelp.html

- url: /.*
  script: index.html

